version: "3"

services:

  f5tt:
    image: fiorucci/f5-telemetry-tracker:latest
    user: "${USERID}:${USERGROUP}"
    container_name: "f5tt-bigiq"
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATAPLANE_TYPE=BIG_IQ
      - DATAPLANE_FQDN=${DATAPLANE_FQDN}
      - DATAPLANE_USERNAME=${DATAPLANE_USERNAME}
      - DATAPLANE_PASSWORD=${DATAPLANE_PASSWORD}

      # Optional HTTP(S) Proxy
      #- HTTP_PROXY="http(s)://username:password@proxy_ip:port"
      #- HTTPS_PROXY="http(s)://username:password@proxy_ip:port"

      # Optional NIST NVD CVE tracking REST API key (https://nvd.nist.gov/developers/request-an-api-key)
      - NIST_API_KEY=${NIST_API_KEY}

      # Optional automated e-mail reporting
      #- EMAIL_ENABLED="true"
      ## Interval in days
      #- EMAIL_INTERVAL=1
      #- EMAIL_SERVER="smtp.mydomain.tld"
      #- EMAIL_SERVER_PORT=25
      ## Server type can be starttls, ssl, plaintext
      #- EMAIL_SERVER_TYPE="starttls"
      ## Optional SMTP authentication
      #- EMAIL_AUTH_USER="username@domain.tld"
      #- EMAIL_AUTH_PASS="thepassword"
      ## Email sender and recipient
      #- EMAIL_SENDER="sender@domain.tld"
      #- EMAIL_RECIPIENT="recipient@domain.tld"

  prometheus:
    image: prom/prometheus
    user: "${USERID}:${USERGROUP}"
    container_name: "prometheus"
    command:
      - '--storage.tsdb.retention.time=730d'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-admin-api'
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /opt/f5tt/prometheus:/prometheus:rw

  grafana:
    image: grafana/grafana
    user: "${USERID}:${USERGROUP}"
    container_name: "grafana"
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./configs/grafana/:/etc/grafana/:ro
      - /opt/f5tt/grafana/data:/var/lib/grafana:rw
      - /opt/f5tt/grafana/log:/var/log/grafana:rw
      - /opt/f5tt/grafana/plugins:/var/lib/grafana/plugins:rw

  nginx:
    image: nginx
    network_mode: "host"
    container_name: "nginx"
    restart: always
    volumes:
      - ./configs/nginx-f5tt-bigiq.conf:/etc/nginx/conf.d/nginx-f5tt.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
